<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ShipRateCalculator.Business</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShipRateCalculator.Domain\ShipRateCalculator.Domain.csproj" />
    <ProjectReference Include="..\ShipRateCalculator.Data\ShipRateCalculator.Data.csproj" />
  </ItemGroup>

</Project>
